### ISSUE TITLE
Need a block explorer

### ISSUE THREAD

**Issue by asdvxgxasjab** [cruzbit/cruzbit#5]
There are a few options. A simple option could be to run a client with `-numminers 0` on the web server serving up the HTML/JS. A more advanced option could be to implement the storage interfaces to include SQL options.

**Comment by icook** [comment]
What's running http://cruzbit.xyz/? If you push it up to Github I can probably push it along a bit.

**Comment by aoea** [comment]
I did that, didn't publish because it's a real mess, wanted to clean it up first. There's something similar on the status branch though.

**Comment by asdvxgxasjab** [comment]
Just rebased and pushed the status branch. The idea with that is to embed the explorer in the client. All of the "go-rice" stuff is just a method for packaging static HTML/JS to serve.

**Comment by Sykh** [comment]
If you tell me how to pull blockdata i can start working on something...

**Comment by asdvxgxasjab** [comment]
We have a few options for this now with https://cruzbase.com and http://cruzplorer.bergbau.pw/index.php. Closing.
