### ISSUE TITLE
get_balances is returning the same pubkey for all balances

### ISSUE THREAD

**Issue by Sykh** [cruzbit/cruzbit#51]
I am sending

`{"type":"get_balances","body":{"public_keys":["++++yuv9msanBuab+ahYCFeg8d8IQD9mmfMAZZWXoSU=","++sUYPnUOlEeJ9i730VTmlG1xJA9odh9cAbRYafway8=","+06me/PKqN37iIgu/UmFFbT7A3QZXZhlXFELOtcFKp8=","+14fb+qo6ZQ8071wFctXMHpQMHvAxBajRsRaaWneQBQ=","+2+nI8336V8ivgPsbe2NHyuRMdHRUyAMsq4BHUIZCs8="]}}`

and my return is

`[{"public_key":"+06me/PKqN37iIgu/UmFFbT7A3QZXZhlXFELOtcFKp8=","balance":15000000000},{"public_key":"+06me/PKqN37iIgu/UmFFbT7A3QZXZhlXFELOtcFKp8=","balance":5000000000},{"public_key":"+06me/PKqN37iIgu/UmFFbT7A3QZXZhlXFELOtcFKp8=","balance":6345599000000},{"public_key":"+06me/PKqN37iIgu/UmFFbT7A3QZXZhlXFELOtcFKp8=","balance":900000000000},{"public_key":"+06me/PKqN37iIgu/UmFFbT7A3QZXZhlXFELOtcFKp8=","balance":30000000000}]`

It is pulling different balances but somehow not iterating over the pubkeys
https://github.com/cruzbit/cruzbit/blob/master/peer.go#L1186

**Comment by asdvxgxasjab** [comment]
Should be fixed with https://github.com/cruzbit/cruzbit/commit/2504723bc73a2de01ff9a502fea76a94b7e97700. Please close it out if you confirm it. Thanks!

**Comment by Sykh** [comment]
Yep its working now, cheers.
